<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);

require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/db.php';

require_role(['superadmin', 'analyst', 'viewer']);

use Dompdf\Dompdf;

function h($value) {
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}

$rows = [];
$result = $conn->query("
    SELECT page, event, COUNT(*) AS total_events, COUNT(DISTINCT cid) AS unique_visitors
    FROM analytics
    WHERE page IS NOT NULL AND page <> '' AND event IS NOT NULL AND event <> ''
    GROUP BY page, event
    ORDER BY total_events DESC
    LIMIT 50
");

if ($result) {
    $rows = $result->fetch_all(MYSQLI_ASSOC);
}

$comments = [];
$stmt = $conn->prepare("
    SELECT author, comment, created
    FROM report_comments
    WHERE report_type = ?
    ORDER BY created DESC
");
$report_type = 'behavior';
$stmt->bind_param("s", $report_type);
$stmt->execute();
$res = $stmt->get_result();
while ($row = $res->fetch_assoc()) {
    $comments[] = $row;
}
$stmt->close();

$html = '
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        h1, h2 { margin-bottom: 8px; }
        .meta { margin-bottom: 16px; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; margin-bottom: 20px; }
        th, td { border: 1px solid #ccc; padding: 8px; text-align: left; vertical-align: top; }
        th { background: #f2f2f2; }
        .comment { border-left: 4px solid #999; padding-left: 10px; margin-bottom: 12px; }
    </style>
</head>
<body>
    <h1>Behavior Report</h1>
    <div class="meta">
        Generated at: ' . h(date('Y-m-d H:i:s')) . '<br>
        Generated by: ' . h($_SESSION['username'] ?? 'unknown') . '
    </div>

    <h2>Page and Event Breakdown</h2>

    <table>
        <thead>
            <tr>
                <th>Page</th>
                <th>Event</th>
                <th>Total Events</th>
                <th>Unique Visitors</th>
            </tr>
        </thead>
        <tbody>';

if (count($rows) > 0) {
    foreach ($rows as $row) {
        $html .= '
            <tr>
                <td>' . h($row['page']) . '</td>
                <td>' . h($row['event']) . '</td>
                <td>' . h($row['total_events']) . '</td>
                <td>' . h($row['unique_visitors']) . '</td>
            </tr>';
    }
} else {
    $html .= '
        <tr>
            <td colspan="4">No behavior data found.</td>
        </tr>';
}

$html .= '
        </tbody>
    </table>

    <h2>Analyst Comments</h2>';

if (count($comments) > 0) {
    foreach ($comments as $comment) {
        $html .= '
            <div class="comment">
                <strong>' . h($comment['author']) . '</strong> (' . h($comment['created']) . ')<br>
                ' . nl2br(h($comment['comment'])) . '
            </div>';
    }
} else {
    $html .= '<p>No comments found for this report.</p>';
}

$html .= '
</body>
</html>';

$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream('behavior_report.pdf', ['Attachment' => true]);
exit;
?>
